<?php

namespace App\Http\Controllers\Internal;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateDesignStatusRequest;
use App\Models\Notification;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DesignController extends Controller
{
    public function index()
    {
        $orders = Order::with(['user', 'designRequest', 'statusHistories.changedBy.role'])
            ->whereIn('status', ['disetujui', 'di_design'])
            ->latest()
            ->get()
            ->map(function ($order) {
                $dr = $order->designRequest;
                $revision = $order->statusHistories->first(fn($h) => str_starts_with($h->notes ?? '', 'Revisi:'));
                $priority = $dr?->priority ?? 'normal';

                // History notes with origin
                $autoGeneratedPrefixes = [
                    'Status berubah menjadi',
                    'Produksi:',
                    'Design selesai',
                    'Pembayaran divalidasi',
                    'Desain disetujui',
                ];
                $historyNotes = [];
                foreach ($order->statusHistories as $h) {
                    $note = $h->notes;
                    if (empty($note)) continue;

                    $isAuto = false;
                    foreach ($autoGeneratedPrefixes as $prefix) {
                        if (str_starts_with($note, $prefix)) { $isAuto = true; break; }
                    }
                    if ($isAuto) continue;

                    $roleName = $h->changedBy?->role?->name;
                    $origin = match ($roleName) {
                        'Design'   => 'Design',
                        'Customer' => 'Customer',
                        'Produksi' => str_contains($note, 'printing') ? 'Produksi (Printing)'
                                    : (str_contains($note, 'jahit')    ? 'Produksi (Jahit)'
                                    : (str_contains($note, 'qc') || str_contains($note, 'QC') ? 'Produksi (QC)' : 'Produksi')),
                        null       => 'Sistem',
                        default    => $roleName,
                    };

                    $historyNotes[] = [
                        'date'   => $h->created_at->format('j M Y, H:i'),
                        'user'   => $h->changedBy?->name ?? 'Sistem',
                        'origin' => $origin,
                        'note'   => $note,
                    ];
                }

                return [
                    'id'                => $order->id,
                    'order_id'          => $order->order_number,
                    'customer'          => $order->user->name ?? '-',
                    'customer_contact'  => $order->user->phone ?? '-',
                    'team_name'         => $dr?->team_name ?? 'Jersey Custom',
                    'deadline'          => $order->created_at->addDays(7)->format('d M Y'),
                    'priority'          => $priority,
                    'revision_note'     => $revision?->notes
                        ? str_replace('Revisi: ', '', $revision->notes)
                        : null,
                    'material'          => $dr?->material ?? '-',
                    'collar'            => $dr?->collar_style ?? '-',
                    'pattern'           => $dr?->motif ?? '-',
                    'jenis_potongan'    => $dr?->jenis_potongan ?? '-',
                    'lengan_jahitan'    => $dr?->lengan_jahitan ?? '-',
                    'notes'             => (function () use ($dr, $order) {
                        $raw = $dr?->additional_notes ?? $order->notes ?? '';
                        if (!$raw) return 'Tidak ada catatan';
                        $parts = explode("\n=== Detail Pesanan ===\n", $raw, 2);
                        return isset($parts[1]) && trim($parts[1])
                            ? nl2br(e(trim($parts[1])))
                            : 'Tidak ada catatan';
                    })(),
                    'reference_files'   => array_merge(
                        $dr?->logo ? [asset('storage/' . $dr->logo)] : [],
                        collect($dr?->design_files ?? [])->map(fn($f) => asset('storage/' . $f['path']))->values()->toArray(),
                    ),
                    'history_notes'     => $historyNotes,
                ];
            })
            ->values()
            ->toArray();

        return view('internal.design', compact('orders'));
    }

    public function updateStatus(UpdateDesignStatusRequest $request, Order $order)
    {
        $data = $request->validated();

        $user = auth()->user();

        if (!in_array($user->role->name, ['Design', 'Super Admin', 'Manager'])) {
            return response()->json([
                'success' => false,
                'message' => 'Anda tidak memiliki izin untuk memperbarui status desain.',
            ], 403);
        }

        // Simpan file upload dengan role SPK
        $uploadedFiles = [];
        $roleMapping = [
            'mockup_files'         => ['mockup_depan', 'mockup_belakang'],
            'detail_depan_files'   => ['detail_depan'],
            'nama_punggung_files'  => ['detail_belakang'],
            'detail_sponsor_files' => ['sponsor'],
        ];

        foreach ($roleMapping as $fieldName => $roles) {
            if ($request->hasFile($fieldName)) {
                $fileIdx = 0;
                foreach ($request->file($fieldName) as $file) {
                    $role = $roles[min($fileIdx, count($roles) - 1)];
                    $path = $file->store('design-files/' . $order->order_number, 'public');
                    $uploadedFiles[] = [
                        'name'     => $file->getClientOriginalName(),
                        'path'     => $path,
                        'size'     => $file->getSize(),
                        'type'     => $file->getMimeType(),
                        'role'     => $role,
                    ];
                    $fileIdx++;
                }
            }
        }

        DB::transaction(function () use ($order, $data, $user, $uploadedFiles) {
            $order->update(['status' => $data['status']]);

            if (!empty($uploadedFiles) && $order->designRequest) {
                $existingFiles = $order->designRequest->design_files ?? [];
                $order->designRequest->update([
                    'design_files' => array_merge($existingFiles, $uploadedFiles),
                ]);
            }

            $notes = 'Design selesai, menunggu SPK';
            if (!empty($uploadedFiles)) {
                $notes .= '. File: ' . implode(', ', array_column($uploadedFiles, 'name'));
            }

            $order->statusHistories()->create([
                'status'     => $data['status'],
                'changed_by' => $user->id,
                'notes'      => $notes,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        });

        Notification::sendToAllStaff(
            'design_upload',
            'Desain Siap — Menunggu SPK',
            "Desain untuk <strong>{$order->order_number}</strong> telah selesai dan menunggu persetujuan SPK oleh Admin.",
            [
                'initials' => collect(explode(' ', $user->name))->map(fn($w) => substr($w, 0, 1))->take(2)->implode(''),
                'role' => $user->role->name,
                'role_initial' => substr($user->role->name, 0, 1),
                'role_color' => '#6b46c1',
                'order_number' => $order->order_number,
            ]
        );

        Notification::sendToCustomer(
            $order->user_id,
            'design_ready',
            'Desain Selesai',
            'Desain untuk pesanan ' . $order->order_number . ' telah selesai dan menunggu persiapan SPK oleh Admin.',
            [
                'order_number' => $order->order_number,
            ]
        );

        return response()->json([
            'success' => true,
            'message' => 'Desain berhasil diselesaikan. File telah dikirim ke SPK untuk ditinjau Admin.',
        ]);
    }
}
